# Generated by Django 4.1 on 2022-08-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
