# Generated by Django 4.1 on 2022-08-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_task_due'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('task_completed', 'task_due')},
        ),
        migrations.AlterField(
            model_name='task',
            name='task_completed',
            field=models.BooleanField(default=False),
        ),
    ]
